# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: builds the executable
    cmds:
      - go build -o travesty cmd/*.go

  clean:
    desc: removes the executable binary
    cmds:
      - rm travesty